#!/bin/bash

# NexaForge AI Model Quick Reference
# Commands untuk setup, check, dan manage AI models

echo "📖 NexaForge AI Model - Quick Reference Commands"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "🔍 CHECK MODEL STATUS"
echo "───────────────────────────────────────────────────────────"
echo "# Check disk space available"
echo "$ df -h"
echo ""
echo "# List all Docker images"
echo "$ docker images"
echo ""
echo "# Check current model cache"
echo "$ ls -lah ~/.cache/huggingface/hub/"
echo ""
echo "# Check if Transformers is installed"
echo "$ python3 -c \"import transformers; print(transformers.__version__)\""
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "📥 DOWNLOAD & INSTALL MODELS"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Option A: Using Ollama (FASTEST & RECOMMENDED)"
echo "────────────────────────────────────────────"
echo "# 1. Start Ollama"
echo "$ docker run -d --name ollama -p 11434:11434 ollama/ollama"
echo ""
echo "# 2. Pull Qwen model (7B recommended for 8GB+ RAM)"
echo "$ docker exec ollama ollama pull qwen:7b-instruct"
echo ""
echo "# 3. Verify model"
echo "$ curl http://localhost:11434/api/tags"
echo ""
echo "# Time: 5-15 minutes"
echo ""
echo ""

echo "Option B: Using Transformers (FULL CONTROL)"
echo "────────────────────────────────────────────"
echo "# 1. Run the setup script"
echo "$ bash /home/whale-d/Unduhan/backup/ai-p/infinite_ai_security/setup-models.sh"
echo ""
echo "# 2. Monitor progress"
echo "$ watch -n 5 'du -sh ~/.cache/huggingface/hub/'"
echo ""
echo "# Time: 15-30 minutes"
echo ""
echo ""

echo "Option C: Manual Transformers Download"
echo "────────────────────────────────────────"
echo "$ python3 << 'EOF'"
echo "from transformers import AutoModelForCausalLM, AutoTokenizer"
echo "model_name = 'Qwen/Qwen2.5-7B-Instruct'"
echo "print('Downloading tokenizer...')"
echo "tokenizer = AutoTokenizer.from_pretrained(model_name)"
echo "print('Downloading model...')"
echo "model = AutoModelForCausalLM.from_pretrained(model_name)"
echo "print('✓ Done!')"
echo "EOF"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🚀 INTEGRATE WITH DOCKER"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "# Create Docker volume for models"
echo "$ docker volume create ai-models"
echo ""
echo "# Copy models to volume"
echo "$ docker run -v ai-models:/models -v ~/.cache:/cache alpine \\"
echo "    cp -r /cache/huggingface/hub /models/"
echo ""
echo "# Update docker-compose-24-7-simplified.yml:"
echo "# Add to api service volumes:"
echo "  volumes:"
echo "    - ai-models:/root/.cache/huggingface/hub"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✅ TEST MODELS"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "# Test Ollama model"
echo "$ curl http://localhost:11434/api/generate -d '{\"model\":\"qwen:7b\",\"prompt\":\"Hello\"}'"
echo ""
echo "# Test Transformers model"
echo "$ python3 << 'EOF'"
echo "from transformers import AutoModelForCausalLM, AutoTokenizer"
echo "model = AutoModelForCausalLM.from_pretrained('Qwen/Qwen2.5-7B-Instruct')"
echo "tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen2.5-7B-Instruct')"
echo "inputs = tokenizer('What is AI?', return_tensors='pt')"
echo "outputs = model.generate(**inputs, max_length=50)"
echo "print(tokenizer.decode(outputs[0]))"
echo "EOF"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🛠️  TROUBLESHOOTING"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Problem: 'Not enough disk space'"
echo "Solution: Free up space or use smaller model (qwen:7b-instruct)"
echo "$ docker system prune -a"
echo ""
echo "Problem: 'Model download stuck'"
echo "Solution: Check internet & retry"
echo "$ docker exec ollama ollama pull qwen:7b-instruct"
echo ""
echo "Problem: 'Out of memory during inference'"
echo "Solution: Use CPU-only mode or smaller model"
echo "# In inference code:"
echo "# device_map = 'cpu'  # instead of 'auto'"
echo ""
echo "Problem: 'Model not found in container'"
echo "Solution: Mount model volume in docker-compose"
echo "$ docker volume inspect ai-models"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📊 MONITOR RESOURCES"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "# Real-time container stats"
echo "$ docker stats"
echo ""
echo "# Check model cache size"
echo "$ du -sh ~/.cache/huggingface/hub/"
echo ""
echo "# Monitor disk usage"
echo "$ watch -n 5 'df -h | grep -E \"^/|Filesystem\"'"
echo ""
echo "# Check memory usage"
echo "$ free -h"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🔗 USEFUL LINKS"
echo "───────────────────────────────────────────────────────────"
echo "Qwen Models: https://huggingface.co/Qwen"
echo "Ollama: https://ollama.ai"
echo "Transformers: https://huggingface.co/docs/transformers"
echo "PyTorch: https://pytorch.org"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
