apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    password: ""
    user: ""
    database: ""
    basicAuth: true
    basicAuthUser: "${GRAFANA_PROMETHEUS_USER}"
    basicAuthPassword: "${GRAFANA_PROMETHEUS_PASSWORD}"
    withCredentials: true
    isDefault: true
    jsonData:
      httpMethod: GET
      timeInterval: 5s
      queryTimeout: 30s
      tlsAuth: true
      tlsAuthWithCACert: true
    secureJsonData:
      tlsCACert: ""
      tlsClientCert: ""
      tlsClientKey: ""
    version: 1
    editable: true